name: Build and test on jerryhobby.com

on:
  workflow_dispatch

jobs:
  build:
    runs-on: jerryhobby.com

    steps:
      - uses: actions/checkout@v3
      - name: Create .env files
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build the application
        run: make build
      - name: Run tests
        run: make test
